### PR TITLE
Jq grid vb

### PR DESCRIPTION
**Pull request by supragyan**
Development of JQGrid enhancement in vb.net
1.Created IJSONService.vb interface to invoking GetProduct data.
2.Created JSONService class and Implemented code to invoking  data from Product table.
3.Created testFxLayerP/table/testJQGridJson.aspx page to display Product data in JQGrid.
4.Added required .css files,js files,images.

### CODE REVIEW

**Comment by daisukenishino** [comment]
>Because, while testing the application we have found that the application retrieving 29 records instead of 30.

The above-mentioned problems have been included in the C # version?

Also, files changed is 104 pcs.
Please pull the latest repository and, create pullrequest.

**Comment by supragyan** [comment]
@daisukenishino 

\>\>Have the above-mentioned problems been included in the C # version?
Yes,in C # version the application retrieving 29 records.
We will soon resolve this issue.
Sorry for inconvenience caused.

Today we were busy with internal work.
We will fix and do code commit by tomorrow.

Please confirm.

**Comment by supragyan** [comment]
@daisukenishino 

\>\>Because, while testing the application we have found that the application retrieving 29 records instead of 30.

we already did maxRows-1 in the following location
https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2010/programs/C%23/Frameworks/Infrastructure/Business/Business/_3TierEngine.cs#L419, 

So we think that maxRows-1 not required in the following location
https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2010/programs/C%23/Samples/WebApp_sample/ProjectX_sample/App_Code/JSONService.svc.cs#L58

We have already tested by removing maxRows-1 in JSONService.svc.cs.
 
Shall we remove maxRows-1 in JSONService.svc.cs ?
Please confirm.

**Comment by daisukenishino** [comment]
@supragyan 

>Shall we remove maxRows-1 in JSONService.svc.cs ?

Yes, Please.

**Comment by supragyan** [comment]
@daisukenishino 

We did remove  maxRows-1 in JSONService.svc.cs.
And also we implemented JQGrid+JSON functionality in vb.net

Shall we commit both C#.net and Vb.net changes in a new feature branch?
Or
Shall we commit C#.net and Vb.net changes in two separate feature branches? 
Is this OK? Please confirm.

**Comment by daisukenishino** [comment]
@supragyan 
Please send one pullrequest that include two change of C # and VB from one repository.

**Comment by supragyan** [comment]
@daisukenishino 

Thank you for confirmation.

We will do so.

**Pull request closed without merging**
