### PR TITLE
Implemented following code to resolve the URL issue in the Frameworks and ProjectX_sample application

### PR DESCRIPTION
**Pull request by SandeepNayak077**
Implemented following code to resolve the URL issue in the Framework
- Implemented ResolveServerUrl method to resolve URL issue of screen transition control, display window and error transition control components
- Modified the relative path in the custom controls for the ImageUrl property
- Modified default relative path of the sample application screens

Modified the following to resolve the URL issue in the application
- Resolved URL issue in the *.master and *.aspx pages of the application
- Modified relative path in the app.config file of the application
- Modified relative path in the *.aspx.cs files to resolve URL issue of display window and screen transition control components
- Modified the relative path in the Server.MapPath to resolve the specified directory path
- Modified relative path in the XML definition file for the screen transition control component
- Resolved URL issue in jQGrid sample by using the ResolveUrl method
- Implemented ResolveServerUrl method to resolve the URL issue in the javascript file

### CODE REVIEW

**Comment by yusukemaegawa** [comment]
@SandeepNayak077 

I am getting the following "Web page error" when trying to access [testNextMasterScreen.aspx](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/url_issue_new/root_VS2013/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/nest/testNestMasterScreen.aspx).

```
Line: 1236
Error: 'baseUrl' is undefined
```

The root master page of testNextMasterScreen.aspx is [rootMasterPage.master](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/url_issue_new/root_VS2013/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testNest/rootMasterPage.master).
rootMasterPage.master does not define the baseUrl variable.
But other master pages define the baseUrl variable as follows.

```html
<!-- Resolve URL in the javascript-->
<script type="text/javascript">
    var baseUrl = "<%= ResolveUrl("~/") %>";
</script>
```

I think you should define the baseUrl variable in rootMasterPage.master.

**Comment by SandeepNayak077** [comment]
@yusukemaegawa 

>https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/73#issuecomment-188015184

I see. 
Okay, we will do this changes and it has been planned as review comment incorporation.
Please continue with the remaining review process.
If there are any other changes, then we will modify all togather and create new pull request.  

Is this OK? 
Please confirm.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

Announcement of additional target. Please check.
- https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/12#issuecomment-189128554

And, please to pull nishino branch from feature branch onece, because this feature branch is old.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/73#issuecomment-189131792

Yes, this contains old version of "nishino" branch.
Because, this pull request sent earlier. 

But, we think merge of this pull request wont affect "nishino" branch.
Because these are independent files, it will olny merge the files related to this task.

However, the remaining activities of this task will be send with new feature branch (created from current latest "nishino" branch.

Please let us know if there is any problem.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>But, we think merge of this pull request wont affect "nishino" branch.

I think so too.
But there is a little worried.

@yusukemaegawa 

Do you think that this correspondence is necessary ?

**Comment by yusukemaegawa** [comment]
@daisukenishino 

I think that whether this correspondence is necessary is case-by-case.

If you modified the same file in "feature brunch 1" and in "feature brunch 2", I think that this correspondence is **necessary**.
In other cases, I think that this correspondence is **unnecessary**.

Just to make sure, I will check the above.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

>If you modified the same file in "feature brunch 1" and in "feature brunch 2", I think that this correspondence is **necessary**.
>In other cases, I think that this correspondence is **unnecessary**.

The above hypothesis was correct.
Therefore, you don't have to pull nishino brunch to feature brunch this time.
But, in other cases, because conflict may occur, you had better pull nishino brunch and send pull request from now on.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

As mentioned above, since the review and check will be easily.
Therefor, please execute pull operation before to send the every pull request from now.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Sure, we will create pull request with respect to the current latest nishino branch.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>Sure, we will create pull request with respect to the current latest nishino branch.

There is no need to generate a new pull request.
You should only pull the "nishino branch" from the "url_issue_new branch".

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/73#issuecomment-190529255

Yes our understanding is correct,
We dont create another pull request for [this same changes](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/73).
Please merge this pull request as soon as possible.
Because this will affect the merge work.

We will create new pull request for [this code change](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/73#issuecomment-188015184).
And the URL issue related to the [WSClientWinStore_samples.sln](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS2013/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientWinStore_samples).

Since we are planning for this sprint activity, 
We want the issue number or link, that describes to delete [WSClientSL_samples](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS2013/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientSL_samples) project from all versions of the framework.
Please let us know.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>Please merge this pull request as soon as possible.
Because this will affect the merge work.

I see.
We will quickly merge this pullrequest, after following pullrequest is merged.
https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/35

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/73#issuecomment-190634547
> We will quickly merge this pullrequest, after following pullrequest is merged.
> OpenTouryoProject#35

Okay, thank you for your support.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

I want to do the correspondence of the following Issue, before the merge of this pull request.

- [Remove a samples of the Silverlight and XBAP for to end this support. #157](https://github.com/OpenTouryoProject/OpenTouryo/issues/157)

Is it possible ?
Please hurry if possible.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/73#issuecomment-191242861
> Is it possible ?

Yes sure its possible.
We will create the pull request.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/73#issuecomment-191242861

We are requesting to correspond this review process as soon as possible.
So that we migrate this to root version.
Please let us know.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

We will correspond asap.

**Pull request merged**
