### PR TITLE
Enhance of MyBaseMVController

### PR DESCRIPTION
**Pull request by kishoreandukuri**
Did Enhance of MyBaseMVController
https://github.com/OpenTouryoProject/OpenTouryo/issues/118

### CODE REVIEW

**Comment by daisukenishino** [comment]
There is a easy mistake. Please check the following.
https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/21#issuecomment-155682426

**Comment by yusukemaegawa** [comment]
@daisukenishino 

Please merge the pull request after checking contents properly as much as possible.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

>Please merge the pull request after checking contents properly as much as possible.

Because there is no time, it is impossible at this time.

@kishoreandukuri 

Easy mistake is often.
Is it possible to reduce such mistake ?

**Comment by kishoreandukuri** [comment]
@daisukenishino 

>Is it possible to reduce such mistake ?

sorry for the inconvenience.
As per the indications, we thought, the class 'BaseMVController.cs' should include in Business Project.

In future, when we create new class we will confirm with you.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>As per the indications, we thought, the class 'BaseMVController.cs' should include in Business Project.

By confirming the other implementations,
You can understand what should be added to any location.
Send pullrequest of the this modification as soon as possible.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
We did the changes as per the comments
https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/21#r44501237

Please merge the pull request
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/25

**Pull request merged**
