### PR TITLE
Implementation of DamSqlDbWithMultiShard project to support MultiShardQuery 

### PR DESCRIPTION
**Pull request by supragyan**
Created following in DamSqlDbWithMultiShard project
- Created DamSqlDbWithMultiShard.cs class to support Dam functionality using MultiShardQuery.
- Created MultiShardConfiguration.cs class to implement Shard properties and methods

Modified following in Framework project
- Added code for connectionstring to support Azure SQL database in MyFcBaseLogic.cs 
- Added Object property in ParameterValue class to pass Shards to DamSqlDbWithMultiShard project

### CODE REVIEW

**Comment by daisukenishino** [comment]
@supragyan 

There are several modification request.

#### MyFcBaseLogic class
**OpenTouryoTemplates** repository can not implement additional Dam by default.

Therefore, changes of **MyFcBaseLogic** should be stored in a separate branch for the only need the difference information for template development.

#### BaseParameterValue classes
- Don't customize **BaseParameterValue** as much as possible.
- Customize the **MyParameterValue** if necessary.

And, If you want to modify the constructor,
it will affect the other **ParameterValue** classes.
Therefore, please select overload approach.

#### GetAzureSQLConnectionString method
I think it's unnecessary.

Becasue,
- GetConfigParameter class is a generic class.
- Not suitable to implement the method that specializes in SQLDB.

Please specify directly to **ConnectionString_AzureSQL**.

**Comment by supragyan** [comment]
@daisukenishino 

\>MyFcBaseLogic class
\>OpenTouryoTemplates repository can not implement additional Dam by default.
\>Therefore, changes of MyFcBaseLogic should be stored in a separate branch for the only need the difference information for template development.
Ok. We understood.
We will create separate branch for MyFcBaseLogic changes to support DamSqlDBWithMultiShard.
and will create new pull request.
Do we need to create pull request to nishino branch or to any new branch?
Please confirm.

\>BaseParameterValue classes
\>Don't customize BaseParameterValue as much as possible.
\>Customize the MyParameterValue if necessary.
Sure we will do so.

\>GetAzureSQLConnectionString method
\>I think it's unnecessary.
Ok.We will do so.

**Comment by daisukenishino** [comment]
@supragyan 

>Do we need to create pull request to nishino branch or to any new branch?
Please confirm.

Please send to nishino branch.
However, this will not be merged.
It is used to get diff as follows.

https://github.com/OpenTouryoProject/OpenTouryo/compare/01-71...PartialUpgradeOfIE11Fromv01-71

**Comment by supragyan** [comment]
@daisukenishino 

As per https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/146#issuecomment-214922935 
#### BaseParameterValue classes

\>Don't customize BaseParameterValue as much as possible.
\>Customize the MyParameterValue if necessary.
Next onwards we will take care.

Now we have not customized BaseParameterValue class and MyParameterValue class also.
To passing Shards we used Static property in DamSqlDBWithMultiShard class.

**Comment by supragyan** [comment]
@daisukenishino 

Please close [148 pull request](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/148).
So that we will create new pull request.

**Pull request closed without merging**
