### PR TITLE
Did NuGet correspondence in the frameworks of root_vs2015

### PR DESCRIPTION
**Pull request by SandeepNayak077**
(1) The NuGet's MSBuild-Integrated Solution environment is applied for the fallowing projects

- Frameworks(AllComponent.sln)
 - Business.csproj
 - Framework.csproj
 - Public.csproj
- Dam(AllDam.sln)
 - DamMySQL.csproj
 - DamOraOdp.csproj
 - DamPstGrS.csproj
- Tools
 - DeployZipPackWithHTTP.csproj

(2) The manual <b>/Public/Dll/</b> support in the roor_2015 framework is deprecated, due to NuGet correspondence.
(3) Did auto download of NuGet.exe upon build process.
(4) Implemented proxy support for Nuget package restore.

### CODE REVIEW

**Comment by yusukemaegawa** [comment]
@SandeepNayak077 

Will you include "NuGet.exe" in .nuget folder?

Currently, the latest version of NuGet.exe is downloaded automatically during build.
But, in my environment, I can not download NuGet.exe due to proxy server.
("http_proxy" environment variable is ineffective.)

If I modify NuGet.target as follows, I can download NuGet successfully.

```c#
WebClient webClient = new WebClient();
webClient.Proxy = new WebProxy([Url and port number of proxy server]);
webClient.Proxy.Credentials = new NetworkCredential([User id], [Password]);
webClient.DownloadFile("https://www.nuget.org/nuget.exe", OutputFilename);
```

But, this countermeasure forces developers to modify all "NuGet.target" files.
Therefore, I want you to include "NuGet.exe" in .nuget folder.

If there are other countermeasures, please suggest.

**Comment by SandeepNayak077** [comment]
@yusukemaegawa 

Sorry for the late reply, due to internal work.

> But, this countermeasure forces developers to modify all "NuGet.target" files.
> Therefore, I want you to include "NuGet.exe" in .nuget folder.
> If there are other countermeasures, please suggest.

As for now, we will add NuGet.exe file.
In future, if we get any countermeasures, we will propose you.

**Comment by yusukemaegawa** [comment]
@SandeepNayak077 

>As for now, we will add NuGet.exe file.
>In future, if we get any countermeasures, we will propose you.

That would be fine.

**Comment by SandeepNayak077** [comment]
@yusukemaegawa 
@daisukenishino 

Thank you for the confirmation.

We are requesting to close the [pull request-90](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/90).
We will add NuGet.exe and create new pull request.

And also merge the [pull request-82](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/82), if there is no issues.
We will send next set of pull request.
Please confirm.

**Pull request merged**
