### PR TITLE
Did NuGet correspondence to MVC_Sample and SPA_Sample projects for root_VS2015 edition

### PR DESCRIPTION
**Pull request by SandeepNayak077**
Target:
- Upgraded Newtonsoft.Json to stable 6.0.5 version

### CODE REVIEW

**Comment by daisukenishino** [comment]
@SandeepNayak077 
Please describe detail  for the third party review.

For example, in the following manner.

@yusukemaegawa 

This pullrequest inclide modifitication of the nuget correspondance in the following issue.
This pullrequest has targeted the "sample folder of root_vs2015".

-Improvement of the build system · Issue~
https://github.com/OpenTouryoProject/OpenTouryo/issues/119

**Comment by daisukenishino** [comment]
@SandeepNayak077 

We have one question.
JSON.NET has been corresponding to nuget.
But, dotnetzip and log4net correspondence is not.
Whether these projects are directly using the library of JSON.NET ?

**Comment by daisukenishino** [comment]
@SandeepNayak077 

Finally, I want to remove the packages folder.

If you remove the packages folder from the project of MVC and the SPA at the moment, File Changed is too many. Because of this, I'm going to request the erasure of the packages folder in the next pull request after once merged pull request.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/80#issuecomment-177699572

Ok, we will describe in detail for the next pull request.

> https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/80#issuecomment-177708490

Yes, we understood your concern.
We will investigate, whether the MVC and SPA projects are directly using JSON, dotnetzip and log4net libraries or not.
If they have not used directly, then we will uninstall these unnecessary packages from the sample projects. 

I have requested engineer to investigate on this comment.
Soon we will send you the report.

> https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/80#issuecomment-177753702

<b>Our understanding</b>
The following changes must be done on the MVC and SPA samples: 
- Remove packages folder from both MVC and SPA samples
- Do not remove package.config file from the projects or uninstall nuget packages
Because when you build the project, the required packages will be downloaded from the NuGet.

The above changes will affect the direct execution of [this build system](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2015/programs/C%23/10_Build_WebApp_sample.bat#L39).
Because, the packages are restored by using the Visual Studio build process
It is not restored by using this [this build system](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2015/programs/C%23/10_Build_WebApp_sample.bat#L39). 

Please confirm our understanding.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/80#issuecomment-177831854
The above changes will affect the direct execution of [this build system](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2015/programs/C%23/10_Build_WebApp_sample.bat#L39).
Because, the packages are restored by using the Visual Studio build process
It is not restored by using this [this build system](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2015/programs/C%23/10_Build_WebApp_sample.bat#L39). 

Thank you for your important pointed out.

@yusukemaegawa 
Do you have a corresponding proposal?

##### Alternative plan
For example ....
- Remove only packages of sample program.
- To investigate how to run the nuget from a script.

**Comment by yusukemaegawa** [comment]
@daisukenishino 
@SandeepNayak077 

Please see the following article.

[Msbuild Integrated](https://docs.nuget.org/consume/package-restore/msbuild-integrated)

In above article describes the procedure of restoring NuGet packages during build.

But, in case of using Visual Studio 2015, this procedure seemed to change.
Please see the following article.

[How do I Enable NuGet Package Restore in Visual Studio 2015](http://stackoverflow.com/questions/27895504/how-do-i-enable-nuget-package-restore-in-visual-studio-2015)

**Comment by daisukenishino** [comment]
@SandeepNayak077 

If the [above](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/80#issuecomment-178352766) can be adopted, and add a description to the [issue](https://github.com/OpenTouryoProject/OpenTouryo/issues/119).

**Comment by SandeepNayak077** [comment]
@daisukenishino 
@yusukemaegawa 

Thank you for sharing the information.
We will investigate and add a description about the solution to the [issue](https://github.com/OpenTouryoProject/OpenTouryo/issues/119).

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/80#issuecomment-177708490
  
we investigated on the nuget correspondance in the MVC_Sample and SPA_Sample project 
JSON.NET libraries are not directly using by the dotnetzip and log4net.
dotnetzip and log4net is refering from the framework projects .
Hence concluded that JSON.NET,dotnetzip and log4net correspondance is not required in the MVC_Sample and SPA_Sample projects.

Requesting to close this pull request we will send the new pull request by removing the unnessary dlls from the sample projects.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/80#issuecomment-179733105

In review process we found the SPA_Sample project requires JSON.NET library because of [this code](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2015/programs/C%23/Samples/WebApp_sample/SPA_Sample/SPA_Sample/App_Start/WebApiConfig.cs#L29).
But dotnetzip and log4net are not required for SPA_Sample.
Hence retain the JSON.NET library and removing dotnetzip and log4net libraries.

For MVC_Sample dotnetzip and log4net and JSON.NET are not required.
So we are removing all 3 libraries.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

I see. Please do so.

**Pull request closed without merging**
