### PR TITLE
Fixed the issue identified in Global.asax and App_Code for both C# and VB

### PR DESCRIPTION
**Pull request by svkumar2810**
1. Changed the class name of inherits in Global.asax as "ProjectX_sample.Global" from "ProjectX_sample.Global_asax" for root_VS2010-root_VS2015 
2. Renamed the App_Code folders name to be "AppCode" for root_VS2010-root_VS2015

### CODE REVIEW

**Comment by daisukenishino** [comment]
@svkumar2810 

# Pointing out
### Service name of REST API has been changed in VB.
Check whether it is needed the following fixes.

#### JSONService.svc
```VB
﻿<%@ ServiceHost Language="VB" Debug="true" Service="JSONService" CodeBehind="~/App_Code/JSONService.vb" %>
```
▼ ▼ ▼
```VB
<%@ ServiceHost Language="VB" Debug="true" Service="ProjectX_sample.JSONService" CodeBehind="~/AppCode/JSONService.vb" %>
```
####  web.config
```XML
<service name="JSONService">
    <endpoint address="" binding="webHttpBinding" behaviorConfiguration="MyBehavior" contract="IJSONService"/>
```
▼ ▼ ▼
```
<service name="ProjectX_sample.JSONService">
    <endpoint address="" binding="webHttpBinding" behaviorConfiguration="MyBehavior" contract="ProjectX_sample.IJSONService"/>
```

### The default position of CodeBehind file
I think that should be changed to the default position.

The default position of the **JSONService.svc.cs** is the same folder as the **JSONService.svc**.
image

I think that it should be moved to the default position.

### The default name of CodeBehind file
I think that should be changed to the default name.

The default name of CodeBehind of **XXXXX.svc** is to add language's filename extension as the **XXXX.svc.vb** simply.

image

I think that it should be renamed to the default name.

# Check target
- root_VS2010
 - C#
   - moved to App_Code from AppCode * 9
   - changed * 2
     - ProjectX_sample.csproj
     - Global.asax
 - VB
   - moved to App_Code from AppCode * 9
   - changed * 3
     - ProjectX_sample.csproj
     - Global.asax
     - Global.asax.vb
- root_VS2012
 - C#
   - moved to App_Code from AppCode * 11
   - changed * 3
     - ProjectX_sample.csproj
     - Global.asax
     - JSONService.svc
 - VB
   - moved to App_Code from AppCode * 11
   - changed * 5
     - ProjectX_sample.csproj
     - Global.asax
     - Global.asax.vb
     - JSONService.svc
     - web.config
- root_VS2013
 - C#
   - moved to App_Code from AppCode * 11
   - changed * 3
     - ProjectX_sample.csproj
     - Global.asax
     - JSONService.svc
 - VB
   - moved to App_Code from AppCode * 11
   - changed * 5
     - ProjectX_sample.csproj
     - Global.asax
     - Global.asax.vb
     - JSONService.svc
     - web.config
- root_VS2015
 - C#
   - moved to App_Code from AppCode * 11
   - changed * 3
     - ProjectX_sample.csproj
     - Global.asax
     - JSONService.svc
   - added
     applicationhost.config
 - VB
   - moved to App_Code from AppCode * 11
   - changed * 5
     - ProjectX_sample.csproj
     - Global.asax
     - Global.asax.vb
     - JSONService.svc
     - web.config

**Comment by daisukenishino** [comment]
@svkumar2810 

Once merged because there are a lot of fixes.
Please send a pull request for the modification.

**Comment by svkumar2810** [comment]
@daisukenishino 

> Service name of REST API has been changed in VB.
> Check whether it is needed the following fixes.

Yes the fixes were required, because the namespace of the source file changes when converted to web application.
Even when we add service by default the project namespace gets added to it. This is only in VB.

**Example:**

If default service name is **Service1.svc**, the mark up will have the Service Name as **'ProjectName.Service1'** as below,
```xml
<%@ ServiceHost Language="VB" Debug="true" Service="ProjectX_sample.Service1" CodeBehind="Service1.svc.vb" %>
```

> **The default position of CodeBehind file**
The position of the service code behind file was placed in App_Code from the beginning itself. So we did not change the position to maintain the consistency.

Please let us know if you want to change it.

**Comment by daisukenishino** [comment]
@svkumar2810 

I want to the **same state** in C&#35; and VB.

### JSONService.svc and JSONService.svc.**
- File name = JSONService.svc.**  
CodeBehind of XXXXX.svc is to add language's filename extension as the XXXX.svc.** simply.
- File position of JSONService.svc.**
The default position of the JSONService.svc.** is the same folder as the JSONService.svc.

### Service name
- Service name ="ProjectX_sample.Service1"

**Comment by svkumar2810** [comment]
@daisukenishino 

We have implemented the changes as discussed and created the pull request for the same [#181](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/181)

Please review and merge.

Thank you for four valuable suggestions and support.

**Pull request merged**
