### PR TITLE
Did NuGet correspondence in the frameworks of root_vs2015

### PR DESCRIPTION
**Pull request by SandeepNayak077**
The NuGet's MSBuild-Integrated Solution environment is applied for the fallowing projects

- Frameworks(AllComponent.sln)
 - Business.csproj
 - Framework.csproj
 - Public.csproj
- Dam(AllDam.sln)
 - DamMySQL.csproj
 - DamOraOdp.csproj
 - DamPstGrS.csproj
- Tools
 - DeployZipPackWithHTTP.csproj

### CODE REVIEW

**Comment by yusukemaegawa** [comment]
@SandeepNayak077 

When developers use a proxy server, NuGet may not restore packages.
Please see [this article](https://docs.nuget.org/consume/nuget-config-settings#proxy-settings) and consider the countermeasure for a proxy server.
(Speaking personally, I think that the countermeasure using environment variable is good.)

**Comment by SandeepNayak077** [comment]
@yusukemaegawa 

> https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/83#issuecomment-182249011

Thank you for the valuable information.
We do the investigation on your countermeasure and report you.

**Comment by SandeepNayak077** [comment]
@yusukemaegawa 
@daisukenishino 

> https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/83#issuecomment-182249011

This is not possible to test in our environment.
Currently, our organization restricting to set proxy environment.

Please let me know,
What changes needs to be done in z_Common.bat and z_Common2.bat file?
We do the changes according to your suggestion and do code commit.

<h3> Proposal on enable NuGet packages: </h3>

We can remove this [Nuget.exe](https://github.com/SymphonyTeleca/OpenTouryoTemplates/tree/NugetPkg_new/root_VS2015/programs/C%23/Frameworks/Infrastructure/.nuget) from the code commit and set [this property](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/NugetPkg_new/root_VS2015/programs/C%23/Frameworks/Infrastructure/.nuget/NuGet.targets#L16) to true.
So that, when you build solution from either Visual Studio or batch file.
Automatically, the latest NuGet.exe file will be downloaded.

Shall we adopt this proposal?
Please let us know.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Thank you for closing this pull request.

We have removed [this code](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2015/programs/C%23/3_Build_Framework.bat#L33) and did code commit.
But, we did not created the pull request.

Because, we are waiting to get the confirmation for the following two comments
- [Our proposal on enable NuGet packages](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/83#issuecomment-183192873)
- [Code to set the http_proxy environment variable](https://github.com/OpenTouryoProject/OpenTouryo/issues/119#issuecomment-183210829)

Once those comments are confirmed, we will do the required modification and create pull request.

**Pull request closed without merging**
