### PR TITLE
Did NuGet correspondence in the frameworks of root_VS2012

### PR DESCRIPTION
**Pull request by SandeepNayak077**
(1) The NuGet's MSBuild-Integrated Solution environment is applied for the fallowing projects
- Frameworks(AllComponent.sln)
 - Public.csproj
- Dam(AllDam.sln)
 - DamMySQL.csproj
 - DamOraOdp.csproj
 - DamPstGrS.csproj
- Tools
 - DeployZipPackWithHTTP.csproj

(2) The manual <b>/Public/Dll/</b> support in the roor_2012 framework is deprecated, due to NuGet correspondence.
(3) Did auto download of NuGet.exe upon build process.

### CODE REVIEW

**Comment by yusukemaegawa** [comment]
@daisukenishino 

Please revert the merge.
Build error occurs when building SPA_Sample.

**Comment by yusukemaegawa** [comment]
@daisukenishino 
@SandeepNayak077 

There is not proxy setting in batch file.
```bat
@echo --------------------------------------------------
@echo Set the proxy settings of Nuget.
@echo --------------------------------------------------
@rem set http_proxy=http://[username]:[password]@[proxy fqdn or ip address]
```

**Comment by daisukenishino** [comment]
@yusukemaegawa 
@SandeepNayak077 

I would like to correspond by the additional pull request.
Since the @SandeepNayak077 does not have a proxy environment,
I want to ask this corresponds to the @yusukemaegawa.

**Comment by yusukemaegawa** [comment]
@daisukenishino 
@SandeepNayak077 

> https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/126#issuecomment-200596326

You removed "Frameworks\Infrastructure\Public\Dll" folder for this pull request.
But, SPA_Sample is still referring this folder.

[SPA_Sample.csproj](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nuget_2012_framework/root_VS2012/programs/C%23/Samples/WebApp_sample/SPA_Sample/SPA_Sample/SPA_Sample.csproj#L53)
```xml
    <Reference Include="Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\..\Frameworks\Infrastructure\Public\Dll\Newtonsoft.Json.dll</HintPath>
    </Reference>
```

**Comment by yusukemaegawa** [comment]
@daisukenishino 

> Since the @SandeepNayak077 does not have a proxy environment,
> I want to ask this corresponds to the @yusukemaegawa.

I have already told you at [this comment](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/126#issuecomment-200597434).
What do you want to ask?

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I am checking this now.
I am surprised to decrease of ZIP file size.
its size had been become 1/3.

>What do you want to ask?

I think if there is no environment, then it is impossible to try to check.
I am also working in a proxy-free environment in AzureIaaS now.

I think that I will try to fix the file directly at the branch, if you are considering only to fill in the [above](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/126#issuecomment-200597434).

**Comment by yusukemaegawa** [comment]
@daisukenishino 

> I think that I will try to fix the file directly at the branch, if you are considering only to fill in the [above](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/126#issuecomment-200597434).

What do you think [this issue](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/126#issuecomment-200599199)?

**Comment by daisukenishino** [comment]
@SandeepNayak077 
@yusukemaegawa 

I found the following two issues in the proxy-free environment

- ProjectX_sample:

- MVC_Sample
```
ビルドに成功しました。

"...root_VS2013\programs\C#\Samples\WebApp_sample\MVC_Sample\MVC_Sample.sln" (既定のターゲット) (1) -> "...root_VS2013\programs\C#\Samples\WebApp_sample\MVC_Sample\MVC_Sample\MVC_Sample.csproj" (既定のターゲット) (2) -> (ResolveAssemblyReferences ターゲット) -> C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3245: この参照を解決できませんでした。アセンブリ "Newtonsoft.Json" が見つかりませんでした。アセンブリが間違いなくディスクに存在することを確認してください。 コードにこの参照が必要な場合、コンパイル エラーが発生する可能性があります。 [...root_VS2013\programs\C#\Samples\WebApp_sample\MVC_Sample\MVC_Sample\MVC_Sample.csproj]
    1 個の警告
    0 エラー
```

-SPA_Sample
```
ビルドに失敗しました。

"...root_VS2013\programs\C#\Samples\WebApp_sample\SPA_Sample\SPA_Sample.sln" (既定のターゲット) (1) -> "...root_VS2013\programs\C#\Samples\WebApp_sample\SPA_Sample\SPA_Sample\SPA_Sample.csproj" (既定のターゲット) (2) -> (ResolveAssemblyReferences ターゲット) -> C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3245: この参照を解決できませんでした。アセンブリ "Newtonsoft.Json" が見つかりませんでした。アセンブリが間違いなくディスクに存在することを確認してください。 コードにこの参照が必要な場合、コンパイル エラーが発生する可能性があります。 [...root_VS2013\programs\C#\Samples\WebApp_sample\SPA_Sample\SPA_Sample\SPA_Sample.csproj] C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3247: 同じ依存アセンブリの異なるバージョン間での競合が見つかりました。 [...root_VS2013\programs\C#\Samples\WebApp_sample\SPA_Sample\SPA_Sample\SPA_Sample.csproj]

"...root_VS2013\programs\C#\Samples\WebApp_sample\SPA_Sample\SPA_Sample.sln" (既定のターゲット) (1) -> "...root_VS2013\programs\C#\Samples\WebApp_sample\SPA_Sample\SPA_Sample\SPA_Sample.csproj" (既定のターゲット) (2) ->(CoreCompile ターゲット) -> App_Start\WebApiConfig.cs(5,7): error CS0246: 型または名前空間名 'Newtonsoft'が見つかりませんでした。using ディレクティブまたはアセンブリ参照が不足しています。 [...root_VS2013\programs\C#\Samples\WebApp_sample\SPA_Sample\SPA_Sample\SPA_Sample.csproj]

    2 個の警告
    1 エラー
```

**Comment by daisukenishino** [comment]
@yusukemaegawa 

>https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/126#issuecomment-200608478
What do you think [this issue](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/126#issuecomment-200599199)?

If @SandeepNayak077 can see this problem in his environment,
I request additional pull request to the @SandeepNayak077.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Is there a need to write to [Readme.md](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2015) about [proxy settings way](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/126#issuecomment-200597434) at the proxy environment ?

**Comment by yusukemaegawa** [comment]
@daisukenishino 

> Is there a need to write to [Readme.md](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2015) about [proxy settings way](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/126#issuecomment-200597434) at the proxy environment ?

I think that you should do.

**Comment by SandeepNayak077** [comment]
@daisukenishino 
@yusukemaegawa 

> https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/126#issuecomment-200597434

We will add this code about the proxy settings.

> https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/126#issuecomment-200610687

We will investigate on the warnings and create new pull request.
We have tested only for the frameworks executed only (1-4 batch files).
We will resolve it send the pull request soon.

Thank you for the informations.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

see : https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/130#issuecomment-201129963
see : https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/126#issue-142887039

Please merge ASAP.

**Pull request merged**
