### PR TITLE
Merged the code changes from root_2010 to root_VS2012 for C# version

### PR DESCRIPTION
**Pull request by supragyan**
Merged the code changes for below folders from root_VS2010 to root_VS2012 for C# version
- Frameworks
- Samples

### CODE REVIEW

**Comment by supragyan** [comment]
@daisukenishino 

We found below differences by compared between root_2010 and root_2012 but we have not merged.

### \root_VS2010\programs\C#\Frameworks\Infrastructure\Public\Resources\PublicExceptionMessageResource.Designer.cs
```CS
        /// <summary>
        ///   This processing is not Implemented. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("NOT_IMPLEMENTED", resourceCulture);
            }
        }
```

### \root_VS2012\programs\C#\Frameworks\Infrastructure\Public\Resources\PublicExceptionMessageResource.Designer.cs

```CS
         /// <summary>
        ///   This processing is not implemented. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("NOT_IMPLEMENTED", resourceCulture);
            }
        }
```
Difference is **Implemented** vs **implemented.** 

From VS2012 onwards we have merged as **implemented.** .

But in root and root_2010 **Implemented**  is present.

Is this OK or do we need to modify in root and root_2010 ?

Please confirm.

**Comment by daisukenishino** [comment]
@supragyan 

Please be in lowercase because it is detected in the diff.

**Comment by supragyan** [comment]
@daisukenishino 

## Observation
We found differences between ProjectX_sample for root and root_2010 for VB version.

### Differences
In **root/programs/VB/Samples/WebApp_sample/ProjectX_sample/**
- [App_Code/sample/Dao/LayerD](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/VB/Samples/WebApp_sample/ProjectX_sample/App_Code/sample/Dao/LayerD.vb#L61)
```CS
Public Sub New(ByVal dam As BaseDam)
        MyBase.New(dam)
    End Sub
```
**ByVal** is added to parameters when converted ProjectX_sample website to web application because in root web app developed in .Net framework 3.5 in which **ByVal** is displayed by default .

In **root_VS2010/programs/VB/Samples/WebApp_sample/ProjectX_sample**
- [App_Code/sample/Dao/LayerD]
```CS
Public Sub New(dam As BaseDam)
        MyBase.New(dam)
    End Sub
```
Here ByVal is not inserted with parameteres because in .Net framework 4 ByVal is not displayed bydefault.

Same as above happens in other classes also.

Do we need to change (remove ByVal) in **root/programs/VB/Samples/WebApp_sample/ProjectX_sample** ?
or
Do we need to merge from root to root_2010 as it is(including ByVal)?

Please confirm.

**Comment by supragyan** [comment]
@daisukenishino 

>This difference is thought to be caused by the difference in the default value of between versions of SharpDeveloper that we are using as a conversion tool.

We understood.

>I want to adopt fix method that has fewer workload by referencing other part.
Please tell me about fix method that has fewer workload.

Do you want us to fix(Remove ByVal) in root?

Pleasec onfirm.

**Comment by daisukenishino** [comment]
@supragyan 

>Do you want us to fix(Remove ByVal) in root and continue same by merge work?

If the workload to remove ByVal is small, it is YES.

**Comment by supragyan** [comment]
@daisukenishino 

>If the workload to remove ByVal is small, it is YES.

Yes it will take some more time.However we will do so.

**Comment by supragyan** [comment]
@daisukenishino 

We have merged Cross-browser-compatible correspondence of the double submission function changes to root from C# to VB version in [#145](https://github.com/SymphonyTeleca/OpenTouryo/pull/145)

We also removed unwanted ByVal changes from ProjectX_sample and created pull request as [146](https://github.com/SymphonyTeleca/OpenTouryo/pull/146)

Please merge as per below sequence to root for VB version 
### Merge sequence 
1.  https://github.com/SymphonyTeleca/OpenTouryo/pull/145
2.  https://github.com/SymphonyTeleca/OpenTouryo/pull/146

**Pull request merged**
