### PR TITLE
Jq grid

### PR DESCRIPTION
**Pull request by supragyan**
Development of JQGrid+JSON in vb.net
1.Removed maxRowno-1 code in JSONService.cs
2.Created JsONService.vb to fetch Product table data
3.Created IJSONService.vb
4.Created testJQGridJSON page to displaying Product table data
5.Added js files
6.Modified config file

### CODE REVIEW

**Comment by daisukenishino** [comment]
I can not review because, the number of files changed too many.
Please send two pullrequest by divided commit of change in the subject and packages folder in the future.
Please send a file other than the packages folder that has been changed in this time.

**Comment by supragyan** [comment]
@daisukenishino 

Thank you for the information.

In future we will create two feature branches to commit modified files and packages.

\>\>Please send a file other than the packages folder that has been changed in this time.
Now, we will create a new feature branch to commit changed files other than packages.

Please confirm.

**Comment by daisukenishino** [comment]
@supragyan 

I think that two feature branch is not required.

In the beginning, Send first pullrequest by commit the modified packages.
And after it was merged, send second pullrequest by commit the subject changes.

Please reduce the work effort of my acceptance task.

**Comment by supragyan** [comment]
@daisukenishino 

Thank you for confirmation.

We will create one new feature branch and first we will commit packages.
After it has merged we will commit code file changes to same feature branch.
We will do and commit by Friday EOD.

**Comment by supragyan** [comment]
@daisukenishino ,

We did code commit  and created pull request
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/9
We requested to merge the pull request to send the modified code.

Please confirm.

**Comment by daisukenishino** [comment]
@supragyan 

The merge of this Pullrequest has been stop for the previous Pullrequest has not been merged.
 Please wait for a while.

**Comment by supragyan** [comment]
@daisukenishino 

We committed the code changes  of JQGrid in vb and created pull request as https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/10
We requested to review and merge this pull request.
Please confirm.

**Pull request closed without merging**
