### PR TITLE
MSBuild Integration for Samples in root_VS2013 edition

### PR DESCRIPTION
**Pull request by SandeepNayak077**
Implemented MSBuild Integration for Samples in root_VS2013 edition for the below projects.
- MVC_sample
- SPA_sample
- WinAzure_sample
- WinStore_samples

Investigated and removed unused DLLs from the below projects.
- MVC_sample
- SPA_sample

### CODE REVIEW

**Comment by daisukenishino** [comment]
@SandeepNayak077 

Is this pull request corresponding to the #37 ?
[Nuget correspondnce for root_VS2012 and root_VS2013. # 37](https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/37)

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> Is this pull request corresponding to the #37 ?

This corresponding is for [Nuget correspondnce for root_VS2012 and root_VS2013. # 37](https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/37).

**Comment by daisukenishino** [comment]
@SandeepNayak077 

I see.

**Comment by yusukemaegawa** [comment]
@SandeepNayak077 

There is not batch file that builds WinAzure_sample.
(This might not have anything to do with this pull request...)

**Comment by SandeepNayak077** [comment]
@yusukemaegawa 

> https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/121#issuecomment-199628673
> There is not batch file that builds WinAzure_sample.

Does the MSBuild integrated solution is not required in WinAzure_sample?
Please confirm our understanding.

**Comment by yusukemaegawa** [comment]
@SandeepNayak077 

I think that there is no problem in this pull request itself.
But, there is not batch file that builds WinAzure_sample.

So, I think that you should add new batch file builds WinAzure_sample.
(e.g. 11_Build_WinAzure_sample.bat)

@daisukenishino 

Please let me know your opinion.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

This matter of to add the bat file will be corresponded at the [issue of #36](https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/36#issuecomment-199698264).

**Pull request merged**
