### PR TITLE
MSBuild Integration for Samples in root_2012 edition

### PR DESCRIPTION
**Pull request by supragyan**
Implemented MSBuild Integrated solution for following Samples 
- MVC_Sample
- SPA_Sample 
- WinStore_Sample

Investigated and Removed unused dlls from following Samples 
- MVC_Sample
- SPA_Sample

### CODE REVIEW

**Comment by daisukenishino** [comment]
@supragyan 

Is this pull request corresponding to the #37 ?
[Nuget correspondnce for root_VS2012 and root_VS2013. # 37](https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/37)

**Comment by supragyan** [comment]
@daisukenishino

\>Is this pull request corresponding to the #37 ?

This corresponding is for Nuget correspondnce for root_VS2012 and root_VS2013. # 37.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

This corresponding is for [Nuget correspondnce for root_VS2012 and root_VS2013. # 37](https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/37).

**Comment by SandeepNayak077** [comment]
@daisukenishino 

There are two pull request we have created one for root_VS2012 ([PullRequest#120](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/120)) and another for root_VS2013([PullRequest#121](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/121)).

**Pull request merged**
